beforeEach(function () {
    cy.visit('https://www.amazon.com/')
    cy.get('a[id="nav-global-location-popover-link"]', { timeout: 50000 }).click({ force: true })
    cy.wait(2000)
    cy.get('[id="GLUXCountryList"]').select('Italy', { force: true })
    cy.wait(2000)
    cy.get('[name="glowDoneButton"]').click({ force: true })
    cy.wait(2000)
    cy.get('[id="twotabsearchtextbox"]', { timeout: 10000 }).type('chair{enter}')
    cy.wait(2000)
    cy.get('[data-component-type="s-search-result"] h2 a', { timeout: 10000 }).eq(0).click({ force: true })
    cy.wait(2000)
    cy.get('input[id="add-to-cart-button"]', { timeout: 10000 }).click({ force: true })
    cy.get('[id="twotabsearchtextbox"]', { timeout: 10000 }).type('table{enter}')
    cy.wait(2000)
    cy.get('[data-component-type="s-search-result"] h2 a', { timeout: 10000 }).eq(0).click({ force: true })
    cy.wait(2000)
    cy.get('input[id="add-to-cart-button"]', { timeout: 10000 }).click({ force: true })
})
afterEach(function () {
    cy.get('[id="nav-cart"]', { timeout: 10000 }).click({ force: true })
    cy.get('[data-action="delete"] input', { timeout: 10000 }).eq(0).click({force:true})
    cy.wait(3000)
    cy.get('[data-action="delete"] input', { timeout: 10000 }).click({force:true})
})